<?php

namespace App\Modules\SystemSuperadmin\Services;

class BusinessProfilePresetFactory
{
    /**
     * @return array<int, array{name:string,business_type:string,description:string,configuration:array<string,mixed>}>
     */
    public function officialPresets(): array
    {
        return [
            $this->preset('Ferreteria con cotizacion y nota', 'hardware_store', 'Flujo formal: cotizacion obligatoria, nota de venta, caja, bancos, inventario y despachos opcionales.', [
                'identity' => [
                    'business_type' => 'hardware_store',
                    'specific_industry' => 'Ferreteria tecnica o distribuidora con cotizaciones',
                    'uses_product_images' => false,
                    'uses_product_variants' => true,
                    'uses_branches' => true,
                    'uses_pos_points' => true,
                ],
                'modules' => [
                    'quotes' => true,
                    'sales_notes' => true,
                    'pos' => false,
                    'purchases' => true,
                    'quick_purchases' => false,
                    'cash' => true,
                    'banks' => true,
                    'billing' => true,
                    'inventory' => true,
                    'deliveries' => true,
                    'customers' => true,
                    'suppliers' => true,
                    'barcode_labels' => true,
                    'workers' => true,
                    'payroll' => true,
                    'services' => true,
                    'service_orders' => false,
                ],
                'submodules' => [
                    'sales_discounts' => true,
                    'manual_price_change' => true,
                    'advances' => true,
                    'credit' => true,
                    'thermal_printing' => true,
                    'barcode_labels' => true,
                ],
                'capabilities' => [
                    'uses_inventory' => true,
                    'uses_lots' => true,
                    'uses_expiration_dates' => false,
                    'uses_services' => true,
                    'uses_service_orders' => false,
                    'uses_reservations' => false,
                    'requires_customer' => true,
                    'allows_direct_sale' => false,
                    'allows_quote_to_sale' => true,
                    'uses_pos' => false,
                    'requires_cash_session' => true,
                    'uses_cash' => true,
                    'uses_banks' => true,
                    'uses_billing' => true,
                    'uses_price_lists' => true,
                    'uses_printer_profiles' => true,
                ],
                'sales' => [
                    'workflow' => 'quotation_to_sale_note',
                    'quotation_mode' => 'required',
                    'document_main' => 'sale_note',
                    'customer_mode' => 'required',
                    'customer_required' => true,
                    'inventory_discount_timing' => 'sale_note',
                    'price_policy' => 'mixed',
                    'discount_policy' => 'permission',
                    'max_discount_percent' => 10,
                    'credit_limit_policy' => 'warn',
                    'default_credit_limit' => 1000,
                    'negative_stock_policy' => 'never',
                    'visible_columns' => ['description', 'model', 'quantity', 'unit', 'base', 'price', 'subtotal'],
                ],
                'billing' => [
                    'enabled' => true,
                    'invoice_flow' => 'quote_sale_note_invoice',
                    'issue_from' => 'sale_note',
                    'issue_timing' => 'automatic_after_quote_conversion',
                ],
                'purchases' => [
                    'workflow' => 'standard_purchase',
                    'barcode_entry' => false,
                    'allow_create_product' => true,
                    'supplier_mode' => 'optional',
                ],
                'deliveries' => ['mode' => 'optional'],
                'products' => [
                    'catalog_mode' => 'mixed_inventory',
                    'item_types' => ['physical', 'internal_supply', 'service'],
                    'variants_enabled' => true,
                    'barcode_required' => false,
                    'unit_equivalences' => true,
                    'allow_service_items' => true,
                ],
                'services' => [
                    'mode' => 'mixed',
                    'orders_enabled' => false,
                    'technician_required' => false,
                    'evidence_enabled' => false,
                    'warranty_enabled' => false,
                    'signature_enabled' => false,
                ],
                'activation_checklist' => [
                    'minimum_requirements' => ['branch', 'currency', 'cash', 'products', 'units', 'receipt_template'],
                ],
            ]),
            $this->preset('Ferreteria POS', 'hardware_store', 'Ferreteria con venta rapida por POS, compras por barcode y cotizacion opcional.', [
                'identity' => [
                    'business_type' => 'hardware_store',
                    'specific_industry' => 'Ferreteria de mostrador con POS rapido',
                    'uses_product_images' => true,
                    'uses_product_variants' => true,
                    'uses_pos_points' => true,
                ],
                'modules' => [
                    'quotes' => true,
                    'sales_notes' => true,
                    'pos' => true,
                    'quick_purchases' => true,
                    'cash' => true,
                    'banks' => true,
                    'billing' => true,
                    'inventory' => true,
                    'deliveries' => true,
                    'offline_pos' => false,
                ],
                'capabilities' => [
                    'uses_inventory' => true,
                    'uses_lots' => true,
                    'requires_customer' => false,
                    'allows_direct_sale' => true,
                    'allows_quote_to_sale' => true,
                    'uses_pos' => true,
                    'uses_barcode_scanner' => true,
                    'requires_cash_session' => true,
                    'uses_cash' => true,
                    'uses_banks' => true,
                    'uses_billing' => true,
                    'uses_price_lists' => true,
                ],
                'sales' => [
                    'workflow' => 'optional_quotation',
                    'quotation_mode' => 'optional',
                    'document_main' => 'ticket',
                    'customer_mode' => 'optional',
                    'customer_required' => false,
                    'price_policy' => 'branch_price',
                    'discount_policy' => 'permission',
                    'max_discount_percent' => 5,
                    'credit_limit_policy' => 'warn',
                    'negative_stock_policy' => 'role',
                    'negative_stock_roles' => ['superadmin'],
                ],
                'billing' => [
                    'enabled' => true,
                    'invoice_flow' => 'choose_per_sale',
                    'issue_from' => 'manual_choice',
                    'issue_timing' => 'manual',
                ],
                'purchases' => ['workflow' => 'barcode_purchase', 'barcode_entry' => true, 'allow_create_product' => true],
                'pos' => ['scanner_mode' => 'optional', 'customer_prompt' => 'optional'],
                'cash' => ['scope' => 'pos_terminal'],
                'products' => ['catalog_mode' => 'mixed_inventory', 'images_enabled' => true, 'variants_enabled' => true],
            ]),
            $this->preset('Restaurante completo', 'restaurant', 'Mesas, salones, meseros, comandas, recetas, propinas, division de cuenta e impresion por area.', [
                'identity' => [
                    'business_type' => 'restaurant',
                    'specific_industry' => 'Restaurante con atencion en mesa',
                    'uses_product_images' => true,
                    'uses_product_variants' => true,
                    'uses_pos_points' => true,
                    'uses_internal_warehouses' => true,
                ],
                'modules' => [
                    'quotes' => false,
                    'sales_notes' => true,
                    'pos' => true,
                    'purchases' => true,
                    'quick_purchases' => false,
                    'cash' => true,
                    'banks' => true,
                    'inventory' => true,
                    'deliveries' => true,
                    'customers' => true,
                    'suppliers' => true,
                    'restaurant_tables' => true,
                    'kitchen_orders' => true,
                    'recipes' => true,
                    'reservations' => true,
                ],
                'submodules' => [
                    'tips' => true,
                    'delivery' => true,
                    'split_payments' => true,
                    'thermal_printing' => true,
                ],
                'capabilities' => [
                    'uses_inventory' => true,
                    'uses_expiration_dates' => true,
                    'uses_recipes' => true,
                    'uses_reservations' => true,
                    'uses_reservable_resources' => true,
                    'uses_tables' => true,
                    'uses_waiters' => true,
                    'uses_kitchen_orders' => true,
                    'uses_tips' => true,
                    'uses_split_payments' => true,
                    'uses_delivery' => true,
                    'requires_customer' => false,
                    'allows_direct_sale' => true,
                    'uses_pos' => true,
                    'requires_cash_session' => true,
                    'uses_cash' => true,
                    'uses_banks' => true,
                    'uses_commissions' => true,
                    'uses_custom_statuses' => true,
                    'uses_printer_profiles' => true,
                ],
                'sales' => [
                    'workflow' => 'restaurant_table',
                    'quotation_mode' => 'disabled',
                    'document_main' => 'ticket',
                    'customer_mode' => 'optional',
                    'customer_required' => false,
                    'inventory_discount_timing' => 'payment',
                    'price_policy' => 'mixed',
                    'payment_methods_by_flow' => ['sales' => ['cash', 'qr', 'card'], 'pos' => ['cash', 'qr', 'card'], 'collections' => ['cash', 'qr', 'card']],
                ],
                'contacts' => ['customer_mode' => 'optional', 'delivery_address_mode' => 'optional'],
                'pos' => ['scanner_mode' => 'optional', 'customer_prompt' => 'optional', 'payment_flow' => 'single_or_mixed'],
                'products' => [
                    'catalog_mode' => 'restaurant_menu',
                    'item_types' => ['prepared_product', 'internal_supply', 'combo'],
                    'images_enabled' => true,
                    'gallery_enabled' => true,
                    'variants_enabled' => true,
                    'allow_service_items' => false,
                ],
                'reservations' => ['calendar_enabled' => true, 'resource_required' => true, 'advance_mode' => 'optional'],
                'restaurant' => [
                    'mode' => 'full',
                    'tables_enabled' => true,
                    'waiters_enabled' => true,
                    'kitchen_areas' => ['cocina', 'barra', 'caja'],
                    'discount_inventory_at' => 'sale_close',
                    'tips_mode' => 'optional',
                    'split_bill_enabled' => true,
                ],
                'documents' => ['active' => ['ticket_pos', 'kitchen_order', 'cash_closing', 'reservation_receipt']],
                'activation_checklist' => ['minimum_requirements' => ['branch', 'cash', 'tables', 'menu', 'recipes', 'printer_profiles']],
            ]),
            $this->preset('Comida rapida y cafeteria', 'fast_food', 'POS directo sin mesas obligatorias, comanda a cocina/barra, pago rapido y recetas simples.', [
                'identity' => [
                    'business_type' => 'fast_food',
                    'specific_industry' => 'Comida rapida, cafeteria o take away',
                    'uses_product_images' => true,
                    'uses_pos_points' => true,
                ],
                'modules' => [
                    'quotes' => false,
                    'sales_notes' => true,
                    'pos' => true,
                    'purchases' => true,
                    'cash' => true,
                    'banks' => true,
                    'inventory' => true,
                    'deliveries' => true,
                    'restaurant_tables' => false,
                    'kitchen_orders' => true,
                    'recipes' => true,
                    'reservations' => false,
                ],
                'capabilities' => [
                    'uses_inventory' => true,
                    'uses_recipes' => true,
                    'uses_kitchen_orders' => true,
                    'uses_tips' => true,
                    'uses_delivery' => true,
                    'requires_customer' => false,
                    'allows_direct_sale' => true,
                    'uses_pos' => true,
                    'requires_cash_session' => true,
                    'uses_cash' => true,
                    'uses_banks' => true,
                    'uses_printer_profiles' => true,
                ],
                'sales' => ['workflow' => 'restaurant_counter', 'quotation_mode' => 'disabled', 'document_main' => 'ticket', 'customer_mode' => 'optional', 'inventory_discount_timing' => 'payment'],
                'pos' => ['scanner_mode' => 'optional', 'customer_prompt' => 'optional'],
                'products' => ['catalog_mode' => 'restaurant_menu', 'item_types' => ['prepared_product', 'internal_supply', 'combo'], 'images_enabled' => true],
                'restaurant' => ['mode' => 'fast_food', 'tables_enabled' => false, 'waiters_enabled' => false, 'kitchen_areas' => ['cocina', 'barra'], 'tips_mode' => 'optional', 'split_bill_enabled' => false],
                'documents' => ['active' => ['ticket_pos', 'kitchen_order', 'cash_closing']],
                'activation_checklist' => ['minimum_requirements' => ['branch', 'cash', 'menu', 'recipes', 'printer_profiles']],
            ]),
            $this->preset('Servicios profesionales', 'services', 'Agenda, cotizaciones, servicios sin stock obligatorio, anticipos, contratos simples y cobro por hitos.', [
                'identity' => [
                    'business_type' => 'services',
                    'specific_industry' => 'Servicios profesionales o consultoria',
                    'uses_product_images' => false,
                ],
                'modules' => [
                    'quotes' => true,
                    'sales_notes' => true,
                    'pos' => false,
                    'purchases' => false,
                    'quick_purchases' => false,
                    'inventory' => false,
                    'deliveries' => false,
                    'customers' => true,
                    'suppliers' => false,
                    'services' => true,
                    'service_orders' => true,
                    'reservations' => true,
                    'cash' => true,
                    'banks' => true,
                ],
                'capabilities' => [
                    'uses_inventory' => false,
                    'uses_services' => true,
                    'uses_service_orders' => true,
                    'uses_reservations' => true,
                    'uses_reservable_resources' => true,
                    'requires_customer' => true,
                    'allows_direct_sale' => true,
                    'uses_cash' => true,
                    'uses_banks' => true,
                    'uses_commissions' => true,
                    'uses_custom_fields' => true,
                    'uses_custom_statuses' => true,
                    'uses_price_lists' => true,
                ],
                'sales' => ['workflow' => 'service_sale', 'quotation_mode' => 'optional', 'document_main' => 'receipt', 'customer_mode' => 'required', 'inventory_discount_timing' => 'manual', 'price_policy' => 'customer_price', 'credit_limit_policy' => 'block'],
                'purchases' => ['supplier_mode' => 'hidden', 'allow_create_product' => false],
                'products' => ['catalog_mode' => 'services', 'item_types' => ['service', 'digital'], 'allow_service_items' => true, 'unit_equivalences' => false],
                'reservations' => ['calendar_enabled' => true, 'resource_required' => false, 'advance_mode' => 'optional'],
                'services' => ['mode' => 'professional', 'orders_enabled' => true, 'technician_required' => false, 'evidence_enabled' => true, 'warranty_enabled' => false, 'signature_enabled' => true],
                'documents' => ['active' => ['quotation', 'service_order', 'advance_receipt', 'simple_contract']],
                'activation_checklist' => ['minimum_requirements' => ['branch', 'customers', 'services', 'service_states']],
            ]),
            $this->preset('Taller y servicio tecnico', 'technical_service', 'Ordenes de servicio con diagnostico, tecnicos, evidencias, materiales usados, garantia y entrega.', [
                'identity' => [
                    'business_type' => 'technical_service',
                    'specific_industry' => 'Taller o servicio tecnico',
                    'uses_product_images' => true,
                    'uses_internal_warehouses' => true,
                ],
                'modules' => [
                    'quotes' => true,
                    'sales_notes' => true,
                    'pos' => false,
                    'purchases' => true,
                    'inventory' => true,
                    'deliveries' => false,
                    'customers' => true,
                    'suppliers' => true,
                    'services' => true,
                    'service_orders' => true,
                    'reservations' => true,
                    'workers' => true,
                    'payroll' => true,
                ],
                'capabilities' => [
                    'uses_inventory' => true,
                    'uses_services' => true,
                    'uses_service_orders' => true,
                    'uses_reservations' => true,
                    'uses_reservable_resources' => true,
                    'requires_customer' => true,
                    'allows_direct_sale' => true,
                    'requires_cash_session' => false,
                    'uses_cash' => true,
                    'uses_banks' => true,
                    'uses_commissions' => true,
                    'uses_custom_fields' => true,
                    'uses_custom_statuses' => true,
                ],
                'sales' => ['workflow' => 'service_sale', 'quotation_mode' => 'optional', 'document_main' => 'receipt', 'customer_mode' => 'required', 'inventory_discount_timing' => 'manual'],
                'products' => ['catalog_mode' => 'mixed_inventory', 'item_types' => ['service', 'physical', 'internal_supply'], 'allow_service_items' => true, 'images_enabled' => true],
                'reservations' => ['calendar_enabled' => true, 'resource_required' => true, 'advance_mode' => 'optional'],
                'services' => ['mode' => 'technical', 'orders_enabled' => true, 'technician_required' => true, 'evidence_enabled' => true, 'warranty_enabled' => true, 'signature_enabled' => true],
                'documents' => ['active' => ['quotation', 'service_order', 'advance_receipt', 'delivery_receipt']],
                'activation_checklist' => ['minimum_requirements' => ['branch', 'technicians', 'service_states', 'customers']],
            ]),
            $this->preset('Supermercado', 'supermarket', 'POS rapido sin cotizaciones, cliente oculto, caja obligatoria, barcode y venta masiva.', [
                'identity' => ['business_type' => 'supermarket', 'specific_industry' => 'Supermercado o minimarket', 'uses_product_images' => true, 'uses_pos_points' => true],
                'modules' => [
                    'quotes' => false,
                    'sales_notes' => true,
                    'pos' => true,
                    'purchases' => true,
                    'quick_purchases' => true,
                    'cash' => true,
                    'banks' => true,
                    'billing' => true,
                    'inventory' => true,
                    'deliveries' => false,
                    'customers' => false,
                    'payment_promises' => false,
                    'offline_pos' => true,
                ],
                'capabilities' => [
                    'uses_inventory' => true,
                    'uses_expiration_dates' => true,
                    'requires_customer' => false,
                    'allows_direct_sale' => true,
                    'uses_pos' => true,
                    'uses_barcode_scanner' => true,
                    'requires_cash_session' => true,
                    'uses_cash' => true,
                    'uses_banks' => true,
                    'uses_billing' => true,
                    'uses_split_payments' => true,
                    'uses_printer_profiles' => true,
                    'uses_offline_pos' => true,
                ],
                'sales' => ['workflow' => 'pos', 'quotation_mode' => 'disabled', 'document_main' => 'invoice_direct', 'customer_mode' => 'optional', 'customer_required' => false, 'price_policy' => 'branch_price', 'discount_policy' => 'never', 'credit_limit_policy' => 'disabled', 'payment_methods_by_flow' => ['sales' => ['cash', 'qr', 'card'], 'pos' => ['cash', 'qr', 'card'], 'collections' => ['cash', 'qr', 'card']]],
                'billing' => ['enabled' => true, 'invoice_flow' => 'direct_invoice', 'issue_from' => 'pos', 'issue_timing' => 'automatic_direct'],
                'pos' => ['scanner_mode' => 'required', 'offline_mode' => 'local_queue', 'customer_prompt' => 'optional'],
                'products' => ['catalog_mode' => 'barcode_retail', 'item_types' => ['physical'], 'images_enabled' => true, 'barcode_required' => true],
                'cash' => ['scope' => 'pos_terminal', 'allow_offline_cash_sales' => true],
                'activation_checklist' => ['minimum_requirements' => ['branch', 'cash', 'products', 'barcodes', 'pos_terminal']],
            ]),
            $this->preset('Libreria y papeleria', 'stationery', 'Retail con POS, compras rapidas, cliente opcional, productos por barcode y servicios simples opcionales.', [
                'identity' => ['business_type' => 'stationery', 'specific_industry' => 'Libreria, papeleria o bazar', 'uses_product_images' => true],
                'modules' => [
                    'quotes' => true,
                    'sales_notes' => true,
                    'pos' => true,
                    'purchases' => true,
                    'quick_purchases' => true,
                    'cash' => true,
                    'banks' => true,
                    'inventory' => true,
                    'deliveries' => false,
                    'customers' => true,
                    'suppliers' => true,
                ],
                'capabilities' => [
                    'uses_inventory' => true,
                    'requires_customer' => false,
                    'allows_direct_sale' => true,
                    'allows_quote_to_sale' => true,
                    'uses_pos' => true,
                    'uses_barcode_scanner' => true,
                    'requires_cash_session' => true,
                    'uses_cash' => true,
                    'uses_banks' => true,
                    'uses_price_lists' => true,
                ],
                'sales' => ['workflow' => 'optional_quotation', 'quotation_mode' => 'optional', 'document_main' => 'ticket', 'customer_mode' => 'optional', 'discount_policy' => 'always_with_limit', 'max_discount_percent' => 5],
                'purchases' => ['workflow' => 'barcode_purchase', 'barcode_entry' => true],
                'products' => ['catalog_mode' => 'barcode_retail', 'item_types' => ['physical', 'service'], 'images_enabled' => true, 'allow_service_items' => true],
                'activation_checklist' => ['minimum_requirements' => ['branch', 'cash', 'products', 'suppliers']],
            ]),
            $this->preset('Tienda general y ropa', 'clothing_store', 'Tienda con POS, variantes por talla/color, imagenes, listas de precios y devoluciones controladas.', [
                'identity' => ['business_type' => 'clothing_store', 'specific_industry' => 'Tienda general, ropa o accesorios', 'uses_product_images' => true, 'uses_product_variants' => true],
                'modules' => [
                    'quotes' => false,
                    'sales_notes' => true,
                    'pos' => true,
                    'purchases' => true,
                    'quick_purchases' => true,
                    'cash' => true,
                    'banks' => true,
                    'inventory' => true,
                    'deliveries' => true,
                    'customers' => true,
                    'returns' => true,
                ],
                'capabilities' => [
                    'uses_inventory' => true,
                    'requires_customer' => false,
                    'allows_direct_sale' => true,
                    'uses_pos' => true,
                    'uses_barcode_scanner' => true,
                    'requires_cash_session' => true,
                    'uses_cash' => true,
                    'uses_banks' => true,
                    'uses_delivery' => true,
                    'uses_custom_fields' => true,
                    'uses_price_lists' => true,
                    'uses_printer_profiles' => true,
                ],
                'sales' => ['workflow' => 'pos', 'quotation_mode' => 'disabled', 'document_main' => 'ticket', 'customer_mode' => 'optional', 'price_policy' => 'mixed', 'discount_policy' => 'role_limit', 'max_discount_percent' => 10],
                'products' => ['catalog_mode' => 'variants', 'item_types' => ['physical'], 'images_enabled' => true, 'gallery_enabled' => true, 'variants_enabled' => true, 'barcode_required' => true],
                'deliveries' => ['mode' => 'optional'],
                'activation_checklist' => ['minimum_requirements' => ['branch', 'cash', 'products', 'variants']],
            ]),
            $this->preset('Fabrica simple', 'factory', 'Cotizacion, produccion simple, inventario, despacho obligatorio, merma y costeo base.', [
                'identity' => ['business_type' => 'factory', 'specific_industry' => 'Fabrica o produccion simple', 'uses_internal_warehouses' => true],
                'modules' => [
                    'quotes' => true,
                    'sales_notes' => true,
                    'pos' => false,
                    'purchases' => true,
                    'cash' => true,
                    'banks' => true,
                    'inventory' => true,
                    'deliveries' => true,
                    'production' => true,
                    'customers' => true,
                    'suppliers' => true,
                ],
                'capabilities' => [
                    'uses_inventory' => true,
                    'uses_lots' => true,
                    'uses_recipes' => true,
                    'uses_production' => true,
                    'uses_custom_statuses' => true,
                    'requires_customer' => true,
                    'allows_quote_to_sale' => true,
                    'requires_cash_session' => false,
                    'uses_cash' => true,
                    'uses_banks' => true,
                ],
                'sales' => ['workflow' => 'quotation_to_sale_note', 'quotation_mode' => 'optional', 'inventory_discount_timing' => 'delivery', 'price_policy' => 'mixed', 'discount_policy' => 'role_limit', 'credit_limit_policy' => 'block', 'negative_stock_policy' => 'category'],
                'deliveries' => ['mode' => 'required', 'driver_required' => true, 'truck_required' => true],
                'purchases' => ['workflow' => 'order_to_purchase', 'barcode_entry' => false, 'supplier_mode' => 'required'],
                'products' => ['catalog_mode' => 'warehouse', 'item_types' => ['internal_supply', 'finished_product', 'physical'], 'unit_equivalences' => true, 'creation_context' => 'restricted'],
                'production_flow' => ['enabled' => true, 'bom_enabled' => true, 'waste_tracking' => true, 'labor_cost_enabled' => true, 'stages_enabled' => true],
                'activation_checklist' => ['minimum_requirements' => ['branch', 'products', 'bom', 'suppliers', 'delivery_resources']],
            ]),
            $this->preset('Alquileres', 'rentals', 'Reservas de recursos alquilables, garantias, penalidades, entrega, devolucion y estados antes/despues.', [
                'identity' => ['business_type' => 'rentals', 'specific_industry' => 'Alquiler de equipos, canchas, salones o bienes', 'uses_product_images' => true],
                'modules' => [
                    'quotes' => true,
                    'sales_notes' => true,
                    'pos' => false,
                    'purchases' => true,
                    'inventory' => true,
                    'deliveries' => true,
                    'reservations' => true,
                    'rentals' => true,
                    'customers' => true,
                    'suppliers' => true,
                    'cash' => true,
                    'banks' => true,
                ],
                'capabilities' => [
                    'uses_inventory' => true,
                    'uses_reservations' => true,
                    'uses_reservable_resources' => true,
                    'uses_rentals' => true,
                    'uses_custom_fields' => true,
                    'uses_custom_statuses' => true,
                    'requires_customer' => true,
                    'allows_direct_sale' => true,
                    'requires_cash_session' => true,
                    'uses_cash' => true,
                    'uses_banks' => true,
                ],
                'sales' => ['workflow' => 'rental_flow', 'quotation_mode' => 'optional', 'document_main' => 'receipt', 'customer_mode' => 'required', 'inventory_discount_timing' => 'delivery'],
                'products' => ['catalog_mode' => 'rentals', 'item_types' => ['rental', 'physical'], 'images_enabled' => true, 'gallery_enabled' => true],
                'reservations' => ['calendar_enabled' => true, 'resource_required' => true, 'advance_mode' => 'required', 'expiration_enabled' => true],
                'rentals' => ['enabled' => true, 'deposit_required' => true, 'late_penalty_enabled' => true, 'condition_check_required' => true],
                'documents' => ['active' => ['quotation', 'reservation_receipt', 'simple_contract', 'delivery_receipt']],
                'activation_checklist' => ['minimum_requirements' => ['branch', 'resources', 'calendar', 'deposit_policy']],
            ]),
        ];
    }

    /**
     * @return array<int, string>
     */
    public function officialNames(): array
    {
        return collect($this->officialPresets())->pluck('name')->all();
    }

    /**
     * @param array<string, mixed> $configuration
     * @return array{name:string,business_type:string,description:string,configuration:array<string,mixed>}
     */
    private function preset(string $name, string $businessType, string $description, array $configuration): array
    {
        return [
            'name' => $name,
            'business_type' => $businessType,
            'description' => $description,
            'configuration' => BusinessProfileConfiguration::normalized($configuration),
        ];
    }
}
