<?php

namespace App\Modules\SystemSuperadmin\Services;

class BusinessProfileConfiguration
{
    public static function defaults(): array
    {
        return [
            'schema_version' => 2,
            'identity' => [
                'business_type' => 'hardware_store',
                'commercial_name' => null,
                'specific_industry' => null,
                'uses_product_images' => false,
                'uses_product_variants' => false,
                'uses_branches' => true,
                'uses_pos_points' => true,
                'uses_internal_warehouses' => false,
            ],
            'modules' => [
                'quotes' => true,
                'dashboard' => true,
                'alerts' => true,
                'sales_notes' => true,
                'pos' => false,
                'purchases' => true,
                'quick_purchases' => false,
                'cash' => true,
                'cash_flow' => true,
                'banks' => true,
                'billing' => false,
                'inventory' => true,
                'deliveries' => true,
                'customers' => true,
                'suppliers' => true,
                'expenses' => true,
                'returns' => true,
                'payment_promises' => true,
                'reports' => true,
                'exports' => true,
                'production' => false,
                'barcode_labels' => true,
                'workers' => true,
                'payroll' => true,
                'reservations' => true,
                'transfers' => true,
                'offline_pos' => false,
                'services' => false,
                'service_orders' => false,
                'restaurant_tables' => false,
                'kitchen_orders' => false,
                'recipes' => false,
                'combos' => false,
                'rentals' => false,
            ],
            'submodules' => [
                'sales_discounts' => true,
                'manual_price_change' => true,
                'advances' => true,
                'credit' => true,
                'tips' => false,
                'delivery' => false,
                'split_payments' => false,
                'thermal_printing' => true,
                'barcode_labels' => true,
            ],
            'capabilities' => [
                'uses_inventory' => true,
                'uses_lots' => false,
                'uses_expiration_dates' => false,
                'uses_recipes' => false,
                'uses_production' => false,
                'uses_services' => false,
                'uses_service_orders' => false,
                'uses_reservations' => false,
                'uses_reservable_resources' => false,
                'uses_rentals' => false,
                'uses_tables' => false,
                'uses_waiters' => false,
                'uses_kitchen_orders' => false,
                'uses_tips' => false,
                'uses_split_payments' => false,
                'uses_delivery' => false,
                'requires_customer' => true,
                'allows_direct_sale' => false,
                'allows_quote_to_sale' => true,
                'uses_pos' => false,
                'uses_barcode_scanner' => false,
                'requires_cash_session' => true,
                'uses_cash' => true,
                'uses_cash_flow' => true,
                'uses_banks' => true,
                'uses_billing' => false,
                'uses_commissions' => false,
                'uses_custom_fields' => false,
                'uses_custom_statuses' => false,
                'uses_price_lists' => false,
                'uses_printer_profiles' => false,
                'uses_offline_pos' => false,
                'uses_dynamic_entities' => false,
                'uses_dynamic_fields' => false,
                'uses_dynamic_relationships' => false,
                'uses_dynamic_forms' => false,
                'uses_field_level_permissions' => false,
                'uses_attachments' => false,
                'uses_document_templates' => false,
                'uses_automation_rules' => false,
                'uses_approval_flows' => false,
                'uses_report_templates' => false,
                'uses_data_governance' => false,
                'uses_operational_traceability' => false,
                'uses_integrations' => false,
                'uses_health_records' => false,
                'uses_dental_chart' => false,
                'uses_loans' => false,
                'uses_guarantees' => false,
                'uses_projects' => false,
                'uses_construction_calculations' => false,
                'uses_vehicles' => false,
                'uses_equipment_repairs' => false,
                'uses_pet_records' => false,
                'uses_memberships' => false,
                'uses_courses' => false,
            ],
            'feature_flags' => [
                'business_profile_v2_core' => true,
                'dynamic_entities_engine' => false,
                'dynamic_fields_engine' => false,
                'dynamic_relationships_engine' => false,
                'dynamic_forms_engine' => false,
                'dynamic_workflows_engine' => false,
                'reservable_resources_engine' => false,
                'formula_engine' => false,
                'document_engine_v2' => false,
                'report_templates_engine' => false,
                'approval_engine' => false,
                'automation_engine' => false,
                'attachments_engine' => false,
                'field_permissions_engine' => false,
                'advanced_multibranch_engine' => false,
                'integrations_engine' => false,
            ],
            'entities' => [
                'defaults_locked' => true,
                'degraded_mode' => 'read_only_history',
                'definitions' => [],
            ],
            'fields' => [
                'defaults_locked' => true,
                'max_fields_per_entity' => 80,
                'sensitive_fields_require_permission' => true,
                'definitions' => [],
            ],
            'relationships' => [
                'defaults_locked' => true,
                'definitions' => [],
            ],
            'forms' => [
                'defaults_locked' => true,
                'max_forms_per_entity' => 30,
                'flow_specific_required_fields' => true,
                'definitions' => [],
            ],
            'states' => [
                'defaults_locked' => true,
                'definitions' => [],
            ],
            'sales' => [
                'workflow' => 'quotation_to_sale_note',
                'quotation_mode' => 'required',
                'document_main' => 'sale_note',
                'quotation_label' => 'Cotizacion',
                'sale_note_label' => 'Nota de venta',
                'ticket_label' => 'Ticket POS',
                'default_terms' => 'NOTA: NO SE ACEPTAN CAMBIOS NI DEVOLUCIONES.',
                'terms_by_document' => [
                    'quotation' => 'Cotizacion valida solo por el periodo acordado.',
                    'sale_note' => 'NOTA: NO SE ACEPTAN CAMBIOS NI DEVOLUCIONES.',
                    'ticket' => 'Gracias por su compra.',
                ],
                'customer_mode' => 'required',
                'customer_required' => true,
                'allow_occasional_customer' => true,
                'allow_price_override' => 'permission',
                'allow_negative_stock' => false,
                'negative_stock_policy' => 'never',
                'negative_stock_roles' => [],
                'negative_stock_categories' => [],
                'price_policy' => 'base_price',
                'discount_policy' => 'permission',
                'max_discount_percent' => 0,
                'discount_roles' => [],
                'credit_limit_policy' => 'disabled',
                'default_credit_limit' => 0,
                'inventory_discount_timing' => 'sale_note',
                'item_merge_control_enabled' => true,
                'item_merge_rule' => 'same_product_unit_and_measure',
                'visible_columns' => ['description', 'model', 'quantity', 'unit', 'base', 'price', 'subtotal'],
                'allowed_payment_methods' => ['cash', 'qr', 'transfer'],
                'payment_methods_by_flow' => [
                    'sales' => ['cash', 'qr', 'transfer'],
                    'pos' => ['cash', 'qr'],
                    'collections' => ['cash', 'qr', 'transfer'],
                    'purchases' => ['cash', 'qr', 'transfer'],
                    'expenses' => ['cash', 'qr', 'transfer'],
                    'payroll' => ['cash', 'qr', 'transfer'],
                ],
            ],
            'purchases' => [
                'workflow' => 'standard_purchase',
                'barcode_entry' => false,
                'allow_create_product' => true,
                'supplier_mode' => 'optional',
                'register_expense_when_paid' => true,
                'purchase_stock_mode_choice' => true,
            ],
            'contacts' => [
                'customer_mode' => 'required',
                'supplier_mode' => 'optional',
                'multiple_contacts' => false,
                'multiple_addresses' => false,
                'delivery_address_mode' => 'optional',
                'tax_data_required_for_billing' => true,
            ],
            'deliveries' => [
                'mode' => 'optional',
                'driver_required' => false,
                'truck_required' => false,
            ],
            'banks' => [
                'reconciliation_mode' => 'automatic',
                'require_branch_account' => true,
            ],
            'finance' => [
                'accounting_mode' => 'cash_and_banks',
                'uses_accounts_receivable' => true,
                'uses_accounts_payable' => true,
                'uses_cost_centers' => false,
                'profit_report_enabled' => true,
                'fiscal_report_enabled' => false,
            ],
            'billing' => [
                'enabled' => false,
                'mode' => 'computerized_online',
                'document_sector' => 'compra_venta',
                'invoice_flow' => 'sale_note_then_invoice',
                'issue_from' => 'sale_note',
                'issue_timing' => 'manual',
                'offline_behavior' => 'temporary_receipt',
                'require_customer_tax_data' => true,
                'auto_request_cufd' => true,
                'daily_catalog_sync' => true,
                'allow_temporary_receipt' => true,
                'require_product_mapping' => true,
                'block_sale_if_invoice_fails' => true,
            ],
            'pos' => [
                'scanner_mode' => 'optional',
                'cart_merge_rule' => 'same_product_and_unit',
                'offline_mode' => 'disabled',
                'payment_flow' => 'single_or_mixed',
                'customer_prompt' => 'optional',
            ],
            'products' => [
                'catalog_mode' => 'mixed_inventory',
                'item_types' => ['physical'],
                'images_enabled' => false,
                'gallery_enabled' => false,
                'variants_enabled' => false,
                'custom_fields_enabled' => false,
                'barcode_required' => false,
                'barcode_labels' => true,
                'unit_equivalences' => true,
                'allow_service_items' => false,
                'creation_context' => 'inventory_and_purchase',
            ],
            'reservations' => [
                'calendar_enabled' => true,
                'resource_required' => false,
                'advance_mode' => 'optional',
                'expiration_enabled' => false,
                'confirmation_enabled' => true,
                'reminders_enabled' => false,
                'allowed_channels' => ['mostrador', 'telefono', 'whatsapp', 'web', 'mesa', 'delivery'],
                'appointment_kinds' => ['cita', 'reserva', 'servicio', 'mesa', 'consulta', 'evento'],
            ],
            'restaurant' => [
                'mode' => 'disabled',
                'tables_enabled' => false,
                'waiters_enabled' => false,
                'kitchen_areas' => [],
                'discount_inventory_at' => 'sale_close',
                'tips_mode' => 'disabled',
                'split_bill_enabled' => false,
            ],
            'services' => [
                'mode' => 'disabled',
                'orders_enabled' => false,
                'technician_required' => false,
                'evidence_enabled' => false,
                'warranty_enabled' => false,
                'signature_enabled' => false,
            ],
            'rentals' => [
                'enabled' => false,
                'deposit_required' => false,
                'late_penalty_enabled' => false,
                'condition_check_required' => false,
            ],
            'production_flow' => [
                'enabled' => false,
                'bom_enabled' => false,
                'waste_tracking' => false,
                'labor_cost_enabled' => false,
                'stages_enabled' => false,
            ],
            'documents' => [
                'active' => ['quotation', 'sale_note', 'barcode_label'],
                'numbering' => [
                    'by_branch' => true,
                    'by_pos_point' => false,
                    'annual_reset' => false,
                    'fiscal_separate' => true,
                ],
                'templates' => [],
            ],
            'governance' => [
                'soft_delete_by_default' => true,
                'retention_policy' => 'manual',
                'allow_anonymization' => false,
                'sensitive_entities' => ['health_record', 'loan', 'salary', 'guarantee', 'attachment'],
                'export_sensitive_requires_permission' => true,
                'audit_sensitive_reads' => false,
            ],
            'field_permissions' => [
                'mode' => 'role_entity_field',
                'default_sensitive_visibility' => 'deny',
                'rules' => [],
            ],
            'attachments' => [
                'enabled' => false,
                'storage' => 'local_private',
                'max_file_mb' => 10,
                'allowed_types' => ['pdf', 'jpg', 'jpeg', 'png', 'webp'],
                'signed_urls' => true,
                'audit_downloads' => true,
                'retention_policy' => 'entity',
            ],
            'automations' => [
                'enabled' => false,
                'rules' => [],
            ],
            'approvals' => [
                'enabled' => false,
                'rules' => [],
            ],
            'integrations' => [
                'enabled' => false,
                'channels' => [
                    'whatsapp' => false,
                    'email' => false,
                    'siat' => false,
                    'thermal_printers' => false,
                    'barcode_scanners' => false,
                    'scales' => false,
                    'cameras' => false,
                    'external_calendar' => false,
                ],
            ],
            'report_templates' => [
                'enabled' => false,
                'templates' => [],
            ],
            'traceability' => [
                'enabled' => true,
                'capture_operational_responsibles' => false,
                'events' => [
                    'created_by' => true,
                    'prepared_by' => false,
                    'delivered_by' => true,
                    'charged_by' => true,
                    'approved_by' => true,
                    'voided_by' => true,
                    'sensitive_field_changed_by' => true,
                ],
            ],
            'migration' => [
                'preserve_legacy_behavior' => true,
                'legacy_profile_name' => 'Ferreteria con cotizacion y nota de venta',
                'dynamic_structure_version' => 1,
                'allow_destructive_migrations' => false,
                'requires_regression_tests' => true,
            ],
            'performance' => [
                'cache_profile_minutes' => 30,
                'cache_capabilities_minutes' => 60,
                'max_dynamic_fields_per_entity' => 80,
                'precompute_dynamic_reports' => false,
                'paginated_dynamic_lists' => true,
            ],
            'policies' => [
                'data' => [
                    'sensitive_fields' => ['cost', 'salary', 'margin'],
                    'export_requires_permission' => true,
                    'show_costs_permission' => 'inventory.products.manage',
                    'show_financial_reports_permission' => 'reports.view',
                ],
                'voids_returns' => [
                    'requires_permission' => true,
                    'max_hours_after_sale' => 24,
                    'return_stock' => true,
                    'affects_cash' => true,
                    'requires_reason' => true,
                    'fiscal_credit_note' => false,
                ],
                'degraded_mode' => [
                    'inactive_modules_read_only_history' => true,
                    'block_new_records' => true,
                    'allow_historical_reports' => true,
                ],
            ],
            'compatibility' => [
                'last_warnings' => [],
                'last_checked_at' => null,
            ],
            'activation_checklist' => [
                'minimum_requirements' => ['branch', 'currency', 'cash', 'products', 'units'],
                'completed' => [],
            ],
            'cash' => [
                'required_to_sell' => true,
                'scope' => 'user_branch',
                'bank_reconciliation' => true,
                'allow_offline_cash_sales' => false,
            ],
            'inventory' => [
                'always_by_branch' => true,
                'lot_tracking_optional' => true,
                'unit_conversions' => true,
            ],
            'ux' => [
                'context_help' => true,
                'spanish_messages' => true,
                'responsive_tables' => true,
                'demo_mode' => true,
            ],
            'human_resources' => [
                'workers_mode' => 'optional',
                'payroll_enabled' => true,
                'salary_expense_integration' => true,
            ],
        ];
    }

    public static function normalized(array $configuration): array
    {
        return self::replaceRecursive(self::defaults(), $configuration);
    }

    private static function replaceRecursive(array $defaults, array $configuration): array
    {
        foreach ($configuration as $key => $value) {
            if (is_array($value) && isset($defaults[$key]) && is_array($defaults[$key]) && ! array_is_list($value)) {
                $defaults[$key] = self::replaceRecursive($defaults[$key], $value);

                continue;
            }

            $defaults[$key] = $value;
        }

        return $defaults;
    }

    public static function options(): array
    {
        return [
            'businessTypes' => [
                'hardware_store' => 'Ferreteria',
                'restaurant' => 'Restaurante',
                'fast_food' => 'Comida rapida o cafeteria',
                'technical_service' => 'Taller o servicio tecnico',
                'auto_mechanic' => 'Mecanica autos o motos',
                'electronics_repair' => 'Reparacion celulares o computadoras',
                'car_wash' => 'Lavadero de autos',
                'moving_service' => 'Mudanzas',
                'health_clinic' => 'Clinica o consultorio medico',
                'dental_clinic' => 'Odontologia',
                'aesthetic_medicine' => 'Medicina estetica o spa',
                'veterinary' => 'Veterinaria o pet shop',
                'gym' => 'Gimnasio o membresias',
                'education' => 'Cursos o educacion',
                'construction' => 'Arquitectura o construccion',
                'loans' => 'Prestamos o casa de empeno',
                'hotel' => 'Hotel u hospedaje',
                'sports_court' => 'Canchas deportivas',
                'events' => 'Eventos o salones',
                'transport_logistics' => 'Transporte o logistica',
                'agriculture' => 'Agropecuaria simple',
                'rentals' => 'Alquileres',
                'clothing_store' => 'Tienda de ropa',
                'store' => 'Tienda',
                'bookstore' => 'Libreria',
                'stationery' => 'Papeleria',
                'supermarket' => 'Supermercado',
                'distributor' => 'Distribuidora',
                'warehouse' => 'Almacen',
                'factory' => 'Fabrica o produccion',
                'services' => 'Servicios',
                'mixed' => 'Mixto o personalizado',
            ],
            'fieldTypes' => [
                'text' => 'Texto',
                'number' => 'Numero',
                'decimal' => 'Decimal',
                'money' => 'Moneda',
                'percentage' => 'Porcentaje',
                'date' => 'Fecha',
                'time' => 'Hora',
                'datetime' => 'Fecha y hora',
                'boolean' => 'Si/No',
                'select' => 'Seleccion unica',
                'multiselect' => 'Seleccion multiple',
                'file' => 'Archivo',
                'image' => 'Imagen',
                'signature' => 'Firma',
                'location' => 'Ubicacion',
                'phone' => 'Telefono',
                'email' => 'Correo',
                'identity_document' => 'Documento de identidad',
                'tax_id' => 'NIT',
                'barcode' => 'Codigo de barras',
                'calculated_formula' => 'Formula calculada',
                'entity_relation' => 'Relacion con entidad',
            ],
            'fieldPermissionModes' => [
                'role_entity_field' => 'Por rol, entidad y campo',
                'role_branch_entity_field' => 'Por rol, sucursal, entidad y campo',
                'user_override' => 'Permite excepciones por usuario',
            ],
            'attachmentStorageModes' => [
                'local_private' => 'Storage privado local',
                's3_private' => 'S3 o compatible privado',
            ],
            'governanceRetentionPolicies' => [
                'manual' => 'Manual',
                'by_entity' => 'Por entidad',
                'legal_hold' => 'Retencion legal',
            ],
            'formulaOperators' => [
                'add' => 'Suma',
                'subtract' => 'Resta',
                'multiply' => 'Multiplicacion',
                'divide' => 'Division segura',
                'min' => 'Minimo',
                'max' => 'Maximo',
                'round' => 'Redondeo',
                'percentage' => 'Porcentaje',
            ],
            'salesWorkflows' => [
                'quotation_to_sale_note' => 'Cotizacion obligatoria y luego nota de venta',
                'optional_quotation' => 'Cotizacion opcional y venta directa',
                'direct_sale' => 'Venta directa',
                'pos' => 'POS rapido con lector de barras',
                'restaurant_table' => 'Mesa -> comanda -> cuenta -> pago',
                'restaurant_counter' => 'POS directo -> cocina -> pago',
                'service_sale' => 'Venta de servicios',
                'reservation_to_sale' => 'Reserva -> atencion -> cobro',
                'rental_flow' => 'Reserva -> entrega -> devolucion -> cobro final',
            ],
            'quotationModes' => [
                'required' => 'Obligatoria',
                'optional' => 'Opcional',
                'disabled' => 'No usa cotizacion',
            ],
            'documents' => [
                'sale_note' => 'Nota de venta',
                'ticket' => 'Ticket POS',
                'receipt' => 'Recibo interno',
                'invoice_later' => 'Factura en modulo fiscal separado',
                'invoice_direct' => 'Factura directa',
            ],
            'billingFlows' => [
                'quote_sale_note_invoice' => 'Cotizacion -> nota de venta -> factura',
                'sale_note_then_invoice' => 'Nota de venta -> factura',
                'direct_invoice' => 'Venta directa con factura inmediata',
                'choose_per_sale' => 'Escoger en cada venta si se factura',
                'billing_disabled' => 'Sin facturacion fiscal',
            ],
            'billingIssueTimings' => [
                'manual' => 'Manual con boton Emitir factura',
                'automatic_on_sale_note' => 'Automatico al crear nota de venta',
                'automatic_after_quote_conversion' => 'Automatico al convertir cotizacion',
                'automatic_direct' => 'Automatico en venta directa',
            ],
            'saleColumns' => [
                'description' => 'Descripcion',
                'model' => 'Modelo',
                'color' => 'Color',
                'width' => 'Ancho',
                'length' => 'Largo',
                'quantity' => 'Cantidad',
                'unit' => 'Unidad',
                'base' => 'Base calculada',
                'price' => 'Precio',
                'subtotal' => 'Subtotal',
            ],
            'paymentMethodCodes' => [
                'cash' => 'Efectivo',
                'qr' => 'QR',
                'transfer' => 'Transferencia',
                'card' => 'Tarjeta',
                'credit' => 'Credito',
            ],
            'documentTypes' => [
                'quotation' => 'Cotizacion',
                'sale_note' => 'Nota de venta',
                'ticket_pos' => 'Ticket POS',
                'kitchen_order' => 'Orden de cocina',
                'service_order' => 'Orden de servicio',
                'advance_receipt' => 'Recibo de anticipo',
                'reservation_receipt' => 'Recibo de reserva',
                'simple_contract' => 'Contrato simple',
                'siat_invoice' => 'Factura SIAT',
                'credit_note' => 'Nota de credito',
                'delivery_receipt' => 'Comprobante de entrega',
                'barcode_label' => 'Etiqueta barcode',
                'cash_closing' => 'Cierre de caja',
                'medical_record' => 'Ficha medica',
                'dental_chart' => 'Odontograma',
                'medical_prescription' => 'Receta medica',
                'consent_form' => 'Consentimiento',
                'loan_contract' => 'Contrato de prestamo',
                'rental_contract' => 'Contrato de alquiler',
                'guarantee_receipt' => 'Comprobante de garantia',
                'construction_budget' => 'Presupuesto de obra',
                'production_order' => 'Orden de produccion',
            ],
            'sensitiveDataFields' => [
                'cost' => 'Costos',
                'salary' => 'Sueldos',
                'margin' => 'Margenes',
                'tax_data' => 'Datos fiscales',
                'bank_data' => 'Datos bancarios',
                'customer_credit' => 'Credito de clientes',
            ],
            'itemMergeRules' => [
                'same_product_unit_and_measure' => 'Fusionar solo si producto, unidad y medida son iguales',
                'same_product_and_unit' => 'Fusionar si producto y unidad son iguales',
                'never' => 'Nunca fusionar items automaticamente',
            ],
            'negativeStockPolicies' => [
                'never' => 'Nunca permitir stock negativo',
                'global' => 'Permitir segun regla general',
                'role' => 'Permitir solo a roles autorizados',
                'category' => 'Permitir solo en categorias autorizadas',
            ],
            'pricePolicies' => [
                'base_price' => 'Precio base del producto',
                'branch_price' => 'Lista de precios por sucursal',
                'customer_price' => 'Lista de precios por cliente',
                'mixed' => 'Cliente, sucursal y precio base',
            ],
            'discountPolicies' => [
                'never' => 'No permitir descuentos',
                'permission' => 'Solo con permiso',
                'role_limit' => 'Limite por rol',
                'always_with_limit' => 'Todos con limite configurado',
            ],
            'creditLimitPolicies' => [
                'disabled' => 'Sin control de limite de credito',
                'warn' => 'Advertir si supera el limite',
                'block' => 'Bloquear si supera el limite',
            ],
            'inventoryTimings' => [
                'sale_note' => 'Al generar nota de venta',
                'payment' => 'Al cobrar',
                'delivery' => 'Al despachar',
                'manual' => 'Manual',
            ],
            'purchaseWorkflows' => [
                'standard_purchase' => 'Compra tradicional',
                'barcode_purchase' => 'Compra rapida por codigo de barras',
                'order_to_purchase' => 'Orden de compra y recepcion',
            ],
            'entityModes' => [
                'hidden' => 'Oculto',
                'optional' => 'Opcional',
                'required' => 'Obligatorio',
            ],
            'deliveryModes' => [
                'disabled' => 'Sin despachos',
                'optional' => 'Despacho opcional',
                'required' => 'Despacho obligatorio',
            ],
            'bankReconciliationModes' => [
                'disabled' => 'Sin conciliacion bancaria',
                'manual' => 'Registrar pendiente de conciliacion',
                'automatic' => 'Conciliar automaticamente',
            ],
            'scannerModes' => [
                'disabled' => 'No usa lector de barras',
                'optional' => 'Lector opcional',
                'required' => 'Lector obligatorio para POS',
            ],
            'offlineModes' => [
                'disabled' => 'Sin ventas offline',
                'cash_only' => 'Offline solo efectivo',
                'local_queue' => 'Cola local para sincronizar',
            ],
            'catalogModes' => [
                'mixed_inventory' => 'Productos mixtos con inventario',
                'barcode_retail' => 'Retail por codigo de barras',
                'services' => 'Servicios sin stock obligatorio',
                'warehouse' => 'Almacen y distribucion',
                'restaurant_menu' => 'Menu con platos, recetas e insumos',
                'variants' => 'Productos con variantes',
                'rentals' => 'Productos alquilables',
            ],
            'itemTypes' => [
                'physical' => 'Producto fisico',
                'service' => 'Servicio',
                'combo' => 'Combo o paquete',
                'kit' => 'Kit',
                'prepared_product' => 'Producto preparado',
                'internal_supply' => 'Insumo interno',
                'finished_product' => 'Producto terminado',
                'rental' => 'Producto alquilable',
                'digital' => 'Producto digital o intangible',
            ],
            'restaurantModes' => [
                'disabled' => 'No usa restaurante',
                'full' => 'Restaurante completo',
                'fast_food' => 'Comida rapida',
                'coffee_shop' => 'Cafeteria',
                'small_restaurant' => 'Restaurante pequeno',
            ],
            'serviceModes' => [
                'disabled' => 'No usa servicios',
                'quick' => 'Servicios rapidos',
                'technical' => 'Servicios tecnicos',
                'professional' => 'Servicios profesionales',
                'workshop' => 'Taller',
                'maintenance' => 'Mantenimiento recurrente',
            ],
            'accountingModes' => [
                'cash_and_banks' => 'Solo caja y bancos',
                'receivable_payable' => 'Cuentas por cobrar y pagar',
                'cost_centers' => 'Centros de costo por sucursal',
                'fiscal_accounting' => 'Reporte fiscal y contable',
            ],
            'productCreationContexts' => [
                'inventory_only' => 'Solo desde inventario',
                'inventory_and_purchase' => 'Inventario y compras',
                'restricted' => 'Solo usuarios autorizados',
            ],
            'cashScopes' => [
                'user_branch' => 'Caja por usuario y sucursal',
                'branch' => 'Caja por sucursal',
                'pos_terminal' => 'Caja por punto de venta',
            ],
        ];
    }
}
